//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ASPCourse.MVC.Lab08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidId { get; set; }
        public string Name { get; set; }
        public string CreditHead { get; set; }
        public System.DateTime bidDate { get; set; }
    }
}
