//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ASPCourse.MVC.Lab08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditId { get; set; }
        public string Head { get; set; }
        public int Period { get; set; }
        public int Sum { get; set; }
        public int Procent { get; set; }
    }
}
