//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ASPCourse.MVC.ExamTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreID { get; set; }
        public int StudentID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> ScoreResult { get; set; }
        public Nullable<System.DateTime> ScoreDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
